metadata: "../sequences/reference_set/metadata_filtered_6.tsv"
sequences: "../sequences/reference_set/sequences_filtered_6.fasta"
metadata_ww: "../sequences/GR/C.37/1645364665711.metadata.tsv"
sequences_ww:  "../sequences/GR/C.37/C.37_EPI_ISL_2023112.fasta"
k: "1000"
cov_ref_sample: "/Users/ioanna/Projects/CSE3000_wastewater_project/data/SARS-CoV-2-NC_045513.fasta"
abundances: "50"
vocs: "../sequences/GR/P.1/P.1_EPI_ISL_2035339.fasta"
coverage: "100"
bootstraps: "0"
min_ab: "0.1"
