name: lcs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - snakemake
  - biopython
  - minimap2
  - samtools
  - pysam
  - gatk4
  - pyvcf
  - pandas
  - bwa
  - picard-slim
  - cvxpy
  - usher
  - git
  - wget
  - pip
  - pip:
    - ray>=1.7.0

