metadata: "../sequences/USA_BA.1_2022_12_21_2022_12_31/metadata.tsv"
sequences: "../sequences/USA_BA.1_2022_12_21_2022_12_31/sequences.fasta"
metadata_ww: "../sequences/BA.2_metadata.tsv"
sequences_ww:  "../sequences/BA.2_EPI_ISL_10268413.fasta"
k: "1000"
cov_ref_sample: "/Users/ioanna/Projects/CSE3000_wastewater_project/data/SARS-CoV-2-NC_045513.fasta"
abundances: "50"
vocs: "../sequences/BA.1_EPI_ISL_10223811.fasta"
coverage: "100"
bootstraps: "0"
min_ab: "1.0"
